# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ae7b1fe67f67c0c15b2333c4442139804cf7d9f4415ebe8448dd18e31d460f57c4e0e9a401214091899fdce02d8384b27bc72d222f860e5d7770890cf4c4b0fa

test:
  secret_key_base: 3e60325419e6a33f20205217080514e410d19b396015ee2df86ea5814b29796266e76404a8c2a413f61839321cc3cada9d4ba95689d5b130996bad1c062d0461

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
